server:
  port: 8015

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://127.0.0.1:7005/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true   #访问路径可以显示IP地址

#设置feign客户端超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.alone.springcloud.service.OrderService: debug

# OpenFeign 开启 Hystrix 属性
feign:
  hystrix:
    enabled: true