server:
  port: 8014

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://127.0.0.1:7004/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true   #访问路径可以显示IP地址
